try {
	console.log("Setting things up")

} catch (error) {
	core.setFailed(error.message);
}